### ISSUE TITLE
cannot start AR demo for Android project

### ISSUE THREAD

**Issue by geniuscare247** [PacktPublishing/Xamarin.Forms-4-Projects#2]
I execute the demo AR program for Chapter 10.

But it seems doesn't work with following error message.

10-18 06:51:07.428 E/mono    ( 5999): Unhandled Exception:
10-18 06:51:07.428 E/mono    ( 5999): System.Exception: Failed to link vertex shader ARCore() and pixel shader ARCore():
10-18 06:51:07.428 E/mono    ( 5999): Error: uniform cCameraScale specified with different precision in different shaders.
10-18 06:51:07.428 E/mono    ( 5999): . You can omit this exception by subscribing to Urho.Application.UnhandledException event and set Handled property to True.
10-18 06:51:07.428 E/mono    ( 5999): ApplicationOptions: args -w -p "Assets/CoreData" -hd -landscape -portrait 
10-18 06:51:07.428 E/mono    ( 5999):   at Urho.Application.ThrowUnhandledException (System.Exception exc) [0x000de] in <19247555b289498788a9cab9a464683c>:0 
10-18 06:51:07.428 E/mono    ( 5999):   at Urho.Runtime.OnNativeCallback (Urho.CallbackType type, System.IntPtr target, System.IntPtr param1, System.Int32 param2, System.String param3) [0x001f3] in <19247555b289498788a9cab9a464683c>:0 
10-18 06:51:07.428 E/mono    ( 5999):   at (wrapper native-to-managed) Urho.Runtime.OnNativeCallback(Urho.CallbackType,intptr,intptr,int,intptr)
10-18 06:51:07.428 E/mono    ( 5999):   at (wrapper managed-to-native) Urho.Application.Application_Run(intptr)
10-18 06:51:07.428 E/mono    ( 5999):   at Urho.Application.Run () [0x00000] in <19247555b289498788a9cab9a464683c>:0 
10-18 06:51:07.428 E/mono    ( 5999):   at Urho.Droid.UrhoSurface+<>c__DisplayClass15_0.<SetSdlMain>b__0 (System.IntPtr _) [0x00017] in <19247555b289498788a9cab9a464683c>:0 
10-18 06:51:07.428 E/mono    ( 5999):   at (wrapper native-to-managed) Urho.Droid.UrhoSurface+<>c__DisplayClass15_0.<SetSdlMain>b__0(intptr)

I choose Pixel 3 Pei 9.0 (API 28) for Android simulator.

Could you help me for this problem?

**Comment by dhindrik** [comment]
You cannot run it in a simulator, you need a real device. 
![7BC9EE0C-345E-4F34-9680-7D6B4CB9A03F](https://user-images.githubusercontent.com/6691971/96369174-c7b11e80-1158-11eb-86c1-8c9bd00d0ce3.jpeg)
